### ISSUE TITLE
Can't download `renstab` dataset because "taxbills.nyc" is unreachable

### ISSUE THREAD

**Issue by roekatz** [nycdb/nycdb#186]
```
INFO:root:Downloading http://taxbills.nyc/joined.csv to /nycdb/src/data/taxbills_joined.csv
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): taxbills.nyc:80
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by austensen** [comment]
Hey, sorry I missed this for so long! We ended up having to get all the files hosted elsewhere, but the urls in nycdb  have been updated in #192, so you should be all good now.
