### ISSUE TITLE
pluto_latest - dataset schema change

### ISSUE THREAD

**Issue by austensen** [nycdb/nycdb#265]
After noticing that `pluto_latest` wasn't getting updated automatically in our HDC database (#264), I tried to manually run the job but then got this other error. Seems like the dataset columns have changed - we should check the [dataset on open data](https://data.cityofnewyork.us/City-Government/Primary-Land-Use-Tax-Lot-Output-PLUTO-/64uk-42ks) and compare with our [schema definition in nycdb](https://github.com/nycdb/nycdb/blob/main/src/nycdb/datasets/pluto_latest.yml).

```
Downloaded the dataset `pluto_latest`. Loading it into the database...
Creating and entering temporary schema 'temp_pluto_latest_1687289374'.
OrderedDict([('borough', 'BK'), ('block', '7104'), ('lot', '338'), ('communityboard', '315'), ('censustract2010', '400'), ('cb2010', '1000'), ('schooldist', '21'), ('councildistrict', '47'), ('postcode', '11223'), ('firecomp', 'E254'), ('policeprct', '61'), ('healtharea', '8610'), ('sanitboro', '3'), ('sanitsub', '1D'), ('address', '336 AVENUE T'), ('zonedist1', 'R4'), ('zonedist2', ''), ('zonedist3', ''), ('zonedist4', ''), ('overlay1', ''), ('overlay2', ''), ('spdist1', 'OP'), ('spdist2', ''), ('spdist3', ''), ('ltdheight', ''), ('splitzone', 'false'), ('bldgclass', 'A5'), ('landuse', '1'), ('easements', '0'), ('ownertype', ''), ('ownername', 'SULTAN, DANIEL'), ('lotarea', '1720'), ('bldgarea', '992'), ('comarea', '0'), ('resarea', '992'), ('officearea', '0'), ('retailarea', '0'), ('garagearea', '0'), ('strgearea', '0'), ('factryarea', '0'), ('otherarea', '0'), ('areasource', '2'), ('numbldgs', '1'), ('numfloors', '2'), ('unitsres', '1'), ('unitstotal', '1'), ('lotfront', '16'), ('lotdepth', '107.5'), ('bldgfront', '16'), ('bldgdepth', '31'), ('ext', 'N'), ('proxcode', '3'), ('irrlotcode', 'false'), ('lottype', '5'), ('bsmtcode', '2'), ('assessland', '12900'), ('assesstot', '62160'), ('exempttot', '0'), ('yearbuilt', '1950'), ('yearalter1', '0'), ('yearalter2', '0'), ('histdist', ''), ('landmark', ''), ('builtfar', '0.58'), ('residfar', '0.75'), ('commfar', '0'), ('facilfar', '2'), ('borocode', '3'), ('bbl', '3071040338'), ('condono', ''), ('tract2010', '400'), ('xcoord', '991876'), ('ycoord', '157547'), ('latitude', '40.5991031'), ('longitude', '-73.9725388'), ('zonemap', '28c'), ('zmcode', ''), ('sanborn', '314 054'), ('taxmap', '32105'), ('edesignum', ''), ('appbbl', ''), ('appdate', ''), ('plutomapid', '1'), ('version', '23v1.1'), ('sanitdistrict', '15'), ('healthcenterdistrict', '37'), ('firm07flag', ''), ('pfirm15flag', ''), ('geom', ''), ('dcpedited', ''), ('notes', ''), ('bct2020', '3040000'), ('bctcb2020', '30400001000')])
Destroying temporary schema 'temp_pluto_latest_1687289374'.
Alas, an error occurred when loading the dataset `pluto_latest`.
 0rows [00:00, ?rows/s]Traceback (most recent call last):
  File "load_dataset.py", line 410, in <module>
    main()
  File "load_dataset.py", line 406, in main
    load_dataset(dataset)
  File "load_dataset.py", line 344, in load_dataset
    ds.db_import()
  File "/nycdb/src/nycdb/dataset.py", line 73, in db_import
    self.import_schema(schema)
  File "/nycdb/src/nycdb/dataset.py", line 119, in import_schema
    batch = list(itertools.islice(rows, 0, BATCH_SIZE))
  File "/nycdb/src/nycdb/typecast.py", line 194, in cast_rows
    yield self.cast_row(row)
  File "/nycdb/src/nycdb/typecast.py", line 205, in cast_row
    d[column] = self.cast[column.lower()](val)
KeyError: 'bct2020'
```

**Comment by austensen** [comment]
this has already been addressed in #260, I just need to update on the auto-updating system for the HDC db
