### ISSUE TITLE
Columns need updating on speculation watchlist

### ISSUE THREAD

**Issue by austensen** [nycdb/nycdb#318]
it looks like the columns may have changed for the [speculation watchlist](https://github.com/nycdb/nycdb/blob/main/src/nycdb/datasets/speculation_watch_list.yml) - on the auto updater we got this error:

```
Traceback (most recent call last):
  File "/app/load_dataset.py", line 375, in error_handling
    yield
  File "/app/load_dataset.py", line 406, in main
    load_dataset(dataset)
  File "/app/load_dataset.py", line 344, in load_dataset
    ds.db_import()
  File "/usr/local/lib/python3.9/site-packages/nycdb/dataset.py", line 73, in db_import
    self.import_schema(schema)
  File "/usr/local/lib/python3.9/site-packages/nycdb/dataset.py", line 119, in import_schema
    batch = list(itertools.islice(rows, 0, BATCH_SIZE))
  File "/usr/local/lib/python3.9/site-packages/nycdb/typecast.py", line 233, in cast_rows
    yield self.cast_row(row)
  File "/usr/local/lib/python3.9/site-packages/nycdb/typecast.py", line 244, in cast_row
    d[column] = self.cast[column.lower()](val)
KeyError: 'censustract2020from2023'
```

**Comment by austensen** [comment]
duplicate of #354, addressed in #358
